# Generated by Django 6.1.1 on 2026-10-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.buku')),
            ],
        ),
    ]
